can't always extract info

diff --git a/scripts/ytm b/scripts/ytm
--- a/scripts/ytm
+++ b/scripts/ytm
@@ -7,4 +7,9 @@ json=$(yt-dlp -j --no-playlist "$url")
 artist=$(echo "$json" | jq -r '.artist')
 title=$(echo "$json" | jq -r '.title')
 
+if [ "$artist" = "null" ]; then
+    echo "Can't extract info"
+    exit 1
+fi
+
 ym "$url" "$artist" "$title"
